### ISSUE TITLE
Add autocomplete for CSS unicode values

### ISSUE THREAD

**Issue by robneu** [idleberg/atom-icon-fonts#1]
This is awesome and almost exactly what I was looking for when I found it. The only thing I really wish it had was an autocomplete for each icon's [unicode value](http://astronautweb.co/snippet/font-awesome/) to be used in CSS.

It might be a pain to gather everything together, but I'd be willing to help if you could provide some scaffolding for the actual autocomplete functionality.

**Comment by idleberg** [comment]
That's not a bad idea

**Comment by idleberg** [comment]
Have a look at [v2.0.0](https://github.com/idleberg/atom-icon-fonts/releases/tag/v2.0.0)!

**Comment by robneu** [comment]
Wow, nice work!! :100:
