### ISSUE TITLE
Request for extra font: Linux

### ISSUE THREAD

**Issue by fusion809** [idleberg/atom-icon-fonts#4]
Hi,

I would like to request that you add the [font-linux](https://github.com/Lukas-W/font-linux) (`fl`) package to this repo, as it provides icons for:
- Arch Linux
- CentOS
- CoreOS
- Debian
- Fedora
  ...

and several other Linux distributions.

Thanks for your time,
Brenton

**Comment by idleberg** [comment]
Thanks for the hint → [v2.5.0](https://github.com/idleberg/atom-icon-fonts/releases/tag/v2.5.0) 🦄
